---

## RedHat tasks

- name: Install Curl
  yum: name=curl state=present

- name: Install the pygpgme package used to verify GPG signatures
  tags: blackfire
  yum: name=pygpgme state=present

- name: Add Blackfire repository to the configuration
  tags: blackfire
  get_url:
    url: "{{ blackfire_repository }}"
    dest: /etc/yum.repos.d/blackfire.repo

- name: install gpg key
  tags: blackfire
  rpm_key:
    key: https://packagecloud.io/gpg.key
    state: present

- name: Install the blackfire-agent package
  tags: blackfire
  yum: name=blackfire-agent state=present update_cache=yes

- name: Install the blackfire-php package
  tags: blackfire
  yum: name=blackfire-php state=present
