---

language: python
sudo: required

python:
  - 2.7

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=1.9.2
  - ANSIBLE_VERSION=1.9.1
  - ANSIBLE_VERSION=1.9.0.1
  - ANSIBLE_VERSION=1.8.4
  - ANSIBLE_VERSION=1.8.3
  - ANSIBLE_VERSION=1.8.2
  - ANSIBLE_VERSION=1.8.1
  - ANSIBLE_VERSION=1.8
  - ANSIBLE_VERSION=1.7.2
  - ANSIBLE_VERSION=1.7.1
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.6.9
  - ANSIBLE_VERSION=1.6.8
  - ANSIBLE_VERSION=1.6.7
  - ANSIBLE_VERSION=1.6.6
  - ANSIBLE_VERSION=1.6.5
  - ANSIBLE_VERSION=1.6.4
  - ANSIBLE_VERSION=1.6.3
  - ANSIBLE_VERSION=1.6.2
  - ANSIBLE_VERSION=1.6.10
  - ANSIBLE_VERSION=1.6.1
  - ANSIBLE_VERSION=1.6
  - ANSIBLE_VERSION=1.5.5
  - ANSIBLE_VERSION=1.5.4
  - ANSIBLE_VERSION=1.5.3
  - ANSIBLE_VERSION=1.5.2
  - ANSIBLE_VERSION=1.5.1
  - ANSIBLE_VERSION=1.5
  - ANSIBLE_VERSION=1.4.5
  - ANSIBLE_VERSION=1.4.4
  - ANSIBLE_VERSION=1.4.3
  - ANSIBLE_VERSION=1.4.2
  - ANSIBLE_VERSION=1.4.1
  - ANSIBLE_VERSION=1.4

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y php5-common php5-cli php5-fpm

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - gem install serverspec

matrix:
  allow_failures:
    # See https://github.com/ansible/ansible/issues/6412
    #     https://github.com/ansible/ansible/issues/6474
    - env: ANSIBLE_VERSION=1.5.5
    - env: ANSIBLE_VERSION=1.5.4
    - env: ANSIBLE_VERSION=1.5.3
    - env: ANSIBLE_VERSION=1.5.2
    - env: ANSIBLE_VERSION=1.5.1

script:
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
  - rake spec
  - >
    ansible-playbook -i inventory playbook.yml --sudo
    | grep -q 'changed=0.*unreachable=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
